import React from "react";
import ReactDOM from "react-dom";

import InfiniteCarousel from "react-leaf-carousel";

const Siler = () => {
  const btn = document.getElementsByClassName("InfiniteCarouselArrowNext");
  return (
    <div style={{ marginTop: "400px" }}>
      <InfiniteCarousel
        dots={true}
        showSides={true}
        sidesOpacity={0.5}
        sideSize={0.1}
        slidesToScroll={4}
        slidesToShow={4}
        scrollOnDevice={true}
      >
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=904098&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=ef4d9c&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=00ffff&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=91b4c0&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=ebbfbf&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=def1f9&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=cdf2c6&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=9fa616&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=94e1e3&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=29083c&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=ffff99&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://placeholdit.imgix.net/~text?txtsize=20&bg=616161&txtclr=ffffff&txt=215%C3%97215&w=215&h=215"
          />
        </div>
        <div>
          <img
            alt=""
            src="https://www.filmibeat.com/ph-big/2021/01/haripriya-hot_16110403503.jpg"
          />
        </div>
      </InfiniteCarousel>
    </div>
  );
};

export default Siler;
